---
title: "ArcGIS vs. QGIS"
description: |
  A short description of the post.
date: 2022-02-07
draft: true
---


```{r include=FALSE}
library(xml2)
library(tidyverse)
library(lubridate)
library(ggfx)
library(ggtext)
library(ragg)
library(colorspace)

```


```{r include=FALSE}
xml_posts <- xml2::read_xml("/home/nils/Downloads/gis.stackexchange.com/Posts.xml") 

# https://stackoverflow.com/questions/1390568/how-can-i-match-on-an-attribute-that-contains-a-certain-string
get_questions <- function(tags, xml_posts, attrs = c("Id", "Tags", "AnswerCount","AcceptedAnswerId", "PostTypeId", "CreationDate", "ViewCount", "Score")){
  imap_dfr(tags, function(tag, group){
  children_filter <- xml2::xml_find_all(xml_posts, glue::glue("//row[contains(@Tags, '{tag}')]"))

  out_df <- map(attrs, function(attr_i){
    xml2::xml_attr(children_filter,attr = attr_i)
  }) %>%
    set_names(attrs) %>%
    do.call(cbind, .) %>% 
    as_tibble() %>%
    mutate(
      searchtag = tag,
      CreationDate = parse_datetime(CreationDate),
      AnswerCount = as.integer(AnswerCount),
      AcceptedAnswerId = as.integer(AcceptedAnswerId),
      PostTypeId = as.integer(PostTypeId),
      group = group
      )
  })
  
}

arcgis_qgis <- get_questions(c(arcgis = "arcgis", arcgis = "arcpy", qgis = "qgis"),xml_posts)

```


```{r}
arcgis_pa <- arcgis_qgis %>%
  mutate(year = year(CreationDate)) %>%
  filter(year < 2022) %>%
  group_by(year, group) %>%
  count()
```



```{r}
arcgis_qgis_roll <- arcgis_qgis %>%
  mutate(month = as.Date(lubridate::round_date(CreationDate, "month"))) %>% 
  group_by(group, month) %>%
  count() %>%
  group_by(group) %>%
  mutate(roll = zoo::rollmean(n, 12, align = "left", fill = NA)) %>%
  filter(!is.na(roll)) %>%
  ungroup() %>%
  complete(group, month, fill = list(n = 0, roll = 0))




arcgis_qgis_wide <- arcgis_qgis_roll %>%
  group_by(month) %>%
  summarise(
    min = min(roll),
    max = max(roll),
    diff = max - min,
    group = group[which.max(roll)]
  )


# https://coolors.co/palette/ef476f-ffd166-06d6a0-118ab2-073b4c
cols <- c(arcgis = "#06d6a0", qgis = "#ef476f")
bgcol <- "#073b4c"


get_first <- function(vec, comp){
  comps <- vec >= comp
  if(!any(comps)){
    length(comps)
  }else{
    min(which(comps))
  }
}

vlines <- tibble(y =  seq(0, 600, 100), xend = arcgis_qgis_roll$month[map_int(y, ~get_first(arcgis_qgis_roll$roll, .x))], x = rep(min(arcgis_qgis_roll$month),length(y)))


ggplot(arcgis_qgis_roll, aes(month, roll, color = group)) +
  geom_ribbon(
    data = arcgis_qgis_wide,
    aes(x = month, ymin = min, ymax = max, color = group,
        fill = after_scale(darken(desaturate(color, .1), .4, space = "HLS"))),
    alpha = .7, inherit.aes = FALSE
  ) +
  with_blur(
    geom_line(data = ~filter(., group == "arcgis"), 
              color = cols[1], size = 2.5),
    colour = lighten(cols[1], .1), sigma = 3
  ) +
  with_blur(
    geom_line(data = ~filter(., group == "qgis"), 
              color = cols[2], size = 2.5),
    colour = lighten(cols[2], .1), sigma = 3
  )  +
  geom_line(size = 1.5) +
  geom_richtext(
    aes(x = as.Date("2015-06-01"), y = 700,
        label = glue::glue("Monthly <span style='font-family:cinzel;'><b style='color:{cols['arcgis']};font-size:30pt;'>[ArcGIS]</b> & <b style='color:{cols['qgis']};font-size:30pt;'>[QGIS]</b></span> Questions on gis.stackoverflow.com")),
    color = "grey80", size = 7, lineheight = 1.5, family = "Work Sans",
    stat = "unique", fill = NA, label.color = NA
  )  +
  annotate("text", x = as.Date("2015-01-27"), y = 620,vjust = .5, hjust = .5,
             label = "ESRI realeases\nArcGIS Pro 1.0",
             family = "Chivo",
           colour = cols["arcgis"],
             size = 3.8,
             lineheight = .9) +
  geom_segment(aes(x = as.Date("2015-01-27"), xend = as.Date("2015-01-27"), 
                   y = 530, yend = 600),colour = cols["arcgis"]) +
  annotate("text", x = as.Date("2016-10-15"), y = 620,vjust = .5, hjust = .5,
             label = "No. of QGIS Tags\nsurpasses ArcGIS",
             family = "Chivo",
           colour = cols["qgis"],
             size = 3.8,
             lineheight = .9) +
  geom_segment(aes(x = as.Date("2016-10-15"), xend = as.Date("2016-10-15"), 
                   y = 430, yend = 600),colour = cols["qgis"]) +
  geom_segment(data = vlines, aes(x = x, xend = xend, y = y, yend = y), inherit.aes = FALSE,  color = "grey50", linetype = "13") +
  geom_segment(data = filter(arcgis_qgis_wide, month(month) == 1), aes(x = month, xend = month, y = 0, yend = min-10), color = "grey50", linetype = "13") +
  scale_x_date(date_breaks = "year", date_labels = "%Y", expand = c(0, 0))  +
  scale_y_continuous(breaks = vlines$y) +
  scale_color_manual(values = cols) +
  theme_void() +
  theme(
    panel.background = element_rect(fill = "transparent", color = "transparent"),
    plot.background = element_rect(fill = bgcol),
    axis.text = element_text(family = "Cinzel", color = "grey80",
                               size = 10, face = "bold", margin = margin(t = 6)),
    panel.grid.major.x = element_blank(),
    plot.margin = margin(15, 30, 10, 30),
    plot.caption = element_text(family = "Work Sans", color = "grey50", size = 8,
                                hjust = .5, margin = margin(t = 30, b = 0)),
    legend.position = "none"
  )


ggsave("/home/nils/ownCloud/Lehre/Bachelor/RemoteSensing/reveal.js/arcgis-qgis.png",height = 15, width = 30, units = "cm")
```








```{r setup, include=FALSE}
arcgis_qis_extracted <- arcgis_qgis %>%
  mutate(Tags = map(str_match_all(Tags,"<(.*?)>"), ~.x[,2])) 

arcgis_qgis_long <- arcgis_qis_extracted%>% 
  unnest_longer(Tags)

arcgis_qgis_tagscor <- arcgis_qgis_long %>%
  select(Id, Tags) %>%
  split(.$Id) %>%
  map_dfr(function(dat) {
    vec <- dat$Tags
    if (length(vec) > 1) {
      ret <-  apply(combn(sort(vec), 2), 2, function(x) {paste(x[1], x[2], sep = "<->")})
    } else{
    ret <- paste(vec, "", sep = "<->")      
    }
    tibble(tags = ret)
  }) %>%
  group_by(tags) %>%
  count() %>%
  separate(tags, c("tag1", "tag2"), "<->")


library(igraph)
library(ggraph)
arcgis_qgis_tagscor %>%
  slice_max(order_by = n, n = 50) %>%
  # mutate(across(where(is.character), ~str_trim(.,"both")))
  graph_from_data_frame(directed = FALSE) %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_colour = n), show.legend = TRUE) +
  geom_node_point() +
  ggraph::scale_edge_alpha(guide = "none") +
  ggraph::scale_edge_colour_gradient(low = "blue",high = "red") +
  geom_node_label(aes(label = name), vjust = 1, hjust = 1, repel = TRUE) +
  ggraph::theme_graph()







```


