project:
  type: website
  
website:
  title: "Through the looking glass 🔭"
  site-url: https://nils.ratnaweera.net
  description: "Nils' Blog on R, Python and spatial stuff"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Teaching Materials"
        file: teaching.qmd
    right: 
      - href: github.com/ratnanil/
        icon: github
      - href: https://twitter.com/NRatnaweera
        icon: twitter
  page-footer: 
    center: '"The time has come", the Walrus said, "To talk of many things.." - From The Walrus and the Carpenter by Lewis Carroll'
    
format:
  html:
    theme: solar
    css: styles.css