project:
  type: website
  preview:
      port: 4200
website:
  title: "Ratnaweera-XYZ"
  site-url: https://ratnaweera.xyz
  description: "Nils' Blog on R, Python and spatial stuff"
  twitter-card: true
  open-graph: true
  navbar:
    logo: images/mylogo.png
    search: true
    left:
      - text: "{{< fa house size=fw >}} Home"
        file: index.qmd
      - text: "{{< fa rss size=fw >}} Blog"
        file: blog.qmd
      - text: "{{< fa person-chalkboard >}} Teaching"
        file: teaching.qmd
      - text: "{{< fa tablet-screen-button >}} Apps"
        menu:
         - text: "Geodienste-Monitor"
           file: apps/geodienste-kantone/index.qmd
         - text: "StackExchange-Tags"
           file: apps/stackexchange/index.qmd
      - text: "{{< fa feather-pointed >}} About"
        file: CV.qmd
      # - text: "{{< fa link >}} Connect"
      #   menu:
      #     - text: "{{< fa brands github >}} Github"
      #       href: https://github.com/ratnanil/
      # - text: "{{< fa hammer >}} Services"
      #   file: "services.qmd"
    right:
      # - href: https://github.com/ratnanil/
      #   icon: github
      - href: https://twitter.com/NRatnaweera
        icon: twitter
      # - href: https://fosstodon.org/@ratnaweera
      #   icon: mastodon
      # - href: https://stackoverflow.com/users/4139249/ratnanil
        # icon: stack-overflow
  page-footer: 
    center: '"The time has come", the Walrus said, "To talk of many things.." - From The Walrus and the Carpenter by Lewis Carroll'
    
format:
  html:
    theme: solar
    css: styles.css
    