---
title: "Ratnaweera XYZ"
title-block-banner: false
---

<style>
h1{
  display: none
}

.grid-contact{
  display: grid;
  grid-template-columns: repeat(2, minmax(30px, 250px));
  grid-gap: 1rem;
  justify-content: space-evenly;
  margin-top: 2rem;
  margin-bottom: 2rem;
}

.grid-contact > div
{
  border-radius: 10px;
  background-color: #073b4c;
  color: #ADB5BD;
  text-align: center;
  padding: 5px;
  position:relative;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

.grid-contact > div:hover{
  background-color: #157087;
}

.grid-contact > div >a{
  position:absolute; 
  width:100%;
  height:100%;
  top:0;
  left: 0;
  z-index: 1;
  display:flex;
  justify-content:center;
  align-items:center;"

}

.menu-link{
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  padding: 5px 7px 5px 7px;
  border-radius: 5px;
  /* background-color: #073b4c; */
  color: #ADB5BD;
  text-decoration: none;
}

.external{
  text-decoration: none;
}

/* harmonize this with the portfolio css */
a .external::after{
  content: "\f08e";
  font: normal normal normal 14px/1 FontAwesome;
}



</style>


<h3 style="text-align: center"> Hi there 👋  </h3>


I'm Nils Ratnaweera, a freelance data scientist and researcher at the  [Zurich University of Applied Sciences (ZHAW)](https://www.zhaw.ch/en/about-us/person/rata/){.external}. I enjoy using different programming languages to solve complex, real world problems. My tools of choice include `R`, `python`, `gdal`, `ogr2ogr`, `PostgresSQL`, `PostGIS` and more.

If you have a project that you think I can help with, please get in touch. I would love to hear from you!

<div class="grid-contact"> 
<div><i class="fa-solid fa-envelope"></i> Email me<a href="mailto:nils@ratnaweera.xyz"></a></div>
<div><i class="fa-solid fa-calendar-day"></i> Book a slot<a href="https://calendly.com/ratnaweera/60min"></a></div>
</div>

Checkout my [{{< fa film >}} Portfolio](/portfolio.html){.menu-link} and my [{{< fa feather-pointed >}} CV](/cv.html){.menu-link}  to know more about what I do and the tool sets I work with.




